### ISSUE TITLE
Install fails with "Missing ASDF_DOWNLOAD_PATH"

### ISSUE THREAD

**Issue by xgnxs** [grimoh/asdf-starship#16]
Hello!  After adding the starship asdf plugin, attempting to install any version of starship, including latest, gives the "Missing ASDF_DOWNLOAD_PATH" message. asdf version is version: v0.7.8-4a3e3d6 on Ubuntu 20.04.1 LTS (running under WSL2).  `asdf list all starship` shows all available versions, up to 0.50.0 (at the time of writing).  Installing other plugins and versions is successful (for example, sqlite).  Please let me know if you need more information!

**Comment by gr1m0h** [comment]
Hello! @xgnxs 

asdf-vm has been added "download script" since version: 0.8.0. Also, asdf-plugin requires that  "download script".
https://github.com/asdf-vm/asdf/issues/552
https://asdf-vm.com/#/plugins-create?id=required-scripts

I think it's a problem with the asdf-vm version.
Is it possible to upgrade asdf-vm ?

**Comment by xgnxs** [comment]
yep, that fixed it!  sorry, should've made sure I had the latest version!  install works just fine now that I updated to version 0.8.0 of asdf.  thank you!
